#!/usr/bin/perl -w

use strict;

my @clf=();
my $debug;
my @junk=();

exit unless (-f "/usr/local/weblogs/all/access.log"); 
$debug = `mv /usr/local/weblogs/all/access.log /usr/local/weblogs/all/access.log.tmp`;

open (WORK, "/usr/local/weblogs/all/access.log.tmp")
	or die "couldn't open /usr/local/weblogs/all/access.log.tmp : $!\n";

while (<WORK>)
{
        @junk = split(/ /, $_ );
	@clf = splice(@junk, 6);
	chomp (@clf);
	open (CLF, ">>/usr/local/weblogs/all/access.log.clf")
	 or die "couldn't open /usr/local/weblogs/all/access.log.clf : $!\n";
	   print CLF join(" ", @clf), "\n"; 
	close (CLF);

}
close WORK;

$debug = `/usr/local/sbin/cm >> /home/rhelmer/cm.log`;
$debug = `webalizer -d /usr/local/weblogs/all/access.log.clf`;

#open(LOG, ">>/var/log/weblogs/weblogs.log") 
#	or die "$!\n"; 
#print LOG $debug;
#close LOG;
	

# cleanup

$debug = `rm -f /usr/local/weblogs/all/access.log.tmp`;
$debug = `rm -f /usr/local/weblogs/all/access.log.clf`;
sleep 1;

exit;
